eureka:
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://aliyun.hellozjf.com:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: Zjf@1234
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: aliyun.hellozjf.com
    port: 5672
    username: hellozjf
    password: Zjf@1234
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest
  cloud:
    stream:
      bindings:
        input:
          group: group
          destination: exchange
        output:
          group: group
          destination: exchange
        input:
          group: group2
          destination: exchange2
        output:
          group: group2
          destination: exchange2
logging:
  level:
    com.imooc.order: debug
server:
  port: 8100
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
env: dev
girl:
  name: lili
  age: 38
