spring:
  datasource:
    url: jdbc:mysql://aliyun.hellozjf.com:3306/order?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: Zjf@1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: aliyun.hellozjf.com
    port: 6379
  rabbitmq:
    host: aliyun.hellozjf.com
    port: 5672
    username: hellozjf
    password: Zjf@1234
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: exchange
        output:
          destination: exchange
        input2:
          destination: exchange2
        output2:
          destination: exchange2
        productInfoInput:
          destination: productInfo
  zipkin:
    base-url: http://aliyun.hellozjf.com:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
server:
  port: 8100
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.imooc.order: debug
    org.springframework.cloud.openfeign: debug
