spring:
  datasource:
    url: jdbc:mysql://aliyun.hellozjf.com:3306/product?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: Zjf@1234
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: aliyun.hellozjf.com
    port: 5672
    username: hellozjf
    password: Zjf@1234  
  cloud:
    stream:
      bindings:
        productInfoOutput:
          destination: productInfo
  jpa:
    show-sql: true
logging:
  level:
    com.imooc.product: debug
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: "*"