eureka:
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://aliyun.hellozjf.com:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: Zjf@1234
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: aliyun.hellozjf.com
    port: 5672
    username: hellozjf
    password: Zjf@1234  
  cloud:
    stream:
      bindings:
        output:
          destination: productInfo
  jpa:
    show-sql: true
logging:
  level:
    com.imooc.product: debug
server:
  port: 8000